name: ahmed_academy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.5.1
  connectivity_plus: ^6.1.3
  firebase_core: ^3.8.1
  firebase_storage: ^12.4.3
  flutter:
    sdk: flutter
  # bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4
  flutter_spinkit: ^5.2.1
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  motion: ^2.0.1
  pdf: ^3.11.3
  random_string: ^2.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#87d3ff"
  image: "assets/images/Splash.png"
  # android_12:
  #   color: "#42a5f5"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

  fonts:
    - family: Fredoka
      fonts:
        - asset: fonts/Fredoka-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Cabinet
      fonts:
        - asset: fonts/Cabinet.ttf

    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
